### ISSUE TITLE
Describe backup strategies for Aggregate

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#101]

**Comment by ankita240796** [comment]
I'd like to take this up. Can you please guide me with any source from where I can get some extra information about this issue?

**Comment by ankita240796** [comment]
@lognaturel @adammichaelwood  I would like to work this. Can you guide me how can I get some information on this. Thanks!

**Comment by adammichaelwood** [comment]
- Search the existing site first, there might be mentions of this here and there in docs about Aggregate in general. 
 - Search the forum. It is likely other people have asked about it and the responses to those questions will provide some info.
 - ODK Aggregate saves its data in an SQL database. So general information about backing-up databases would be true here, as well. (Though you'd want to to some experimenting around restoring an dODK Aggregate instance from a backedup DB, etc.
 - Google App Engine might have platform-specific back up tools which could be helpful. Since we promote GAE as the "canonical" install approach, we should highlight any backup sgtrategies that would work specifically for the platform.

**Comment by ankita240796** [comment]
Thanks @adammichaelwood !

**Comment by ankita240796** [comment]
@opendatakit-bot claim
