### ISSUE TITLE
problems using HTTP Basic in ODK Aggregate

### ISSUE THREAD

**Issue by jerzyn** [opendatakit/docs#1072]
Hi,

I am trying to retrieve data from ODK Aggregate (v 2.0.3). It works fine with anonymous user access enabled, however when I restricted it to administrator and my user only I cannot access it using HTTP Basic authentication. I am sending my creds in the `Authorization` header, `username:password` base64 encoded, but I always get a `401` response code. In this example I am calling the `/formList`  endpoint (btw. is there any decent API contract documentation, like a Swagger file or something?).  I would appreciate any help :)

**Comment by lognaturel** [comment]
Hi @jerzyn! Please use the forum for support - https://forum.opendatakit.org

Basic auth is not supported over HTTP because it provides no security in that case: https://docs.opendatakit.org/openrosa-authentication/#basic-authentication

If you are trying to build a system around an ODK server, I would encourage you to check out Central: https://docs.opendatakit.org/central-intro/
