### ISSUE TITLE
Point all Oracle Java download links to AdoptOpenJDK.

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#1107]
https://forum.opendatakit.org/t/java-licensing/22125

**Comment by ggalmazor** [comment]
Some thoughts:

- It's generally OK to recommend AdoptOpenJDK's builds to our users, although we should note that any other OpenJDK vendor should do the trick. Users might have other vendors installed already, and dealing with multiple JVMs can be a nuisance.

- We should specify a minimum fully qualified version because we know that some lower patch versions of Java 8 can act up when dealing with crypto.
