### ISSUE TITLE
Unsafe Docker version for Sync Endpoint

### ISSUE THREAD

**Issue by vmaldosan** [opendatakit/docs#1197]
According to the documentation for Sync Endpoint, Docker **17.06.1** or newer is recommended. However, a critical vulnerability (more details at [CVE-2019-5736](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-5736)) was fixed on [18.09.2](https://github.com/docker/docker-ce/releases/tag/v18.09.2), so it might be advisable to update it.

**Comment by vmaldosan** [comment]
This would be a perfect "good-first-issue", but I can take care of it if no one has claimed it in one week :)

**Comment by wbrunette** [comment]
@vmaldosan go ahead and claim it and make the change. @linl33 do we need to change the docker config files?

**Comment by vmaldosan** [comment]
@opendatakit-bot claim

**Comment by linl33** [comment]
The current wording is there to specify the oldest version that works with Sync Endpoint. It should not be interpreted as the recommended version. A version was specified in the documentation because Sync Endpoint requires certain Docker features that were new at the time of writing. Maybe specifying a version is causing more issues than it solve and we should not mention any version instead.

@wbrunette 
We don't need to change the config files.
