### ISSUE TITLE
A brief history of ODK subprojects

### ISSUE THREAD

**Issue by arahayrabedian** [opendatakit/docs#12]
Jumping in to opendatakit in order to build a few things for aggregate and collect I've been struggling with the context of everything.

A few things are in a state of ownership flux, moving (to my understanding) from University of Washington 'ownership' to community driven. A lot of this knowledge is not easy to come by for newcomers - a prime example is Javarosa*, which has one retired-ish version on bitbucket and a recent version on github under odk's wing.

A brief history and current state/status of these project changes would help provide some context when reasoning about how things all fit in together. Leading to less surprises and pointers on where to find the 'current' information on things.

\* : so, e.g with javarosa I had an issue with digging up the [right version](https://github.com/opendatakit/aggregate/blob/master/pom.xml#L419-L425) of it to get aggregate building, had to jump through things referencing each other and get help to figure out what was going on.

**Comment by mitchellsundt** [comment]
The CONFIGURE.md and other documentation has information on building the system.

The maven build is the official build for the installer images. You should follow those instructions to ensure a fully successful standard build.

Active development had been on the uiexperiment branch.  At this point, master, v1_4, and uiexperiment are all at the tip, which is now using the opendatakit.javarosa-2.2.0.jar.

The Tomcat / MySQL / PostgreSQL / SQLServer builds should use Java 8 runtimes due to guava-21.0 dependency (you can back-rev this to 20.0 but SQLServer builds require Java 8 due to the use of 3rd party librares for Linux / MacOSX connectivity support).

The maven build instructions have been updated for the dual Java 7 / Java 8 requirements of the build so that the AppEngine build can be built and tested.

**Comment by adammichaelwood** [comment]
Some of this has been (I hope) solved by the docs home page.

I assume any additional info needed will be available from the new odk site.

Closing this issue.
