### ISSUE TITLE
A doc on using google drive in ODK collect

### ISSUE THREAD

**Issue by nadaa** [opendatakit/docs#164]
I found there is an option to set "google drive" as a server in ODK collect app. I think it will be good to include this in the ODK Docs?

**Comment by lognaturel** [comment]
There currently is this section: http://docs.opendatakit.org/collect-install/#connecting-to-a-googe-drive-account

Some information that should be included is that the Google Drive integration does not support repeats and can handle a maximum of 255 questions because of a Google Sheet limitation.

@adammichaelwood will need to provide guidance on where this information should go when he has a chance!

**Comment by adammichaelwood** [comment]
I think a small doc on using google drive would be worthwhile. 
It could be an independent page for now (`google-drive.rst`) and we can put it under the Collect TOC for now (it can move later without a problem)

@nadaa if you'd like to work on this, that would be great. You'd need to find whatever info is already available, and try to get the process going yourself between an Android device and your own Google drive account. Then write up a guide so other people can do it.

**Comment by nadaa** [comment]
Yes, I will work on it.

**Comment by nadaa** [comment]
@adammichaelwood, I have prepared a doc, shall I send a PR?. @yanokwa, is there any news about Google Earth license?

**Comment by lognaturel** [comment]
In Collect 1.14.0+, Google Drive integration will support repeats. 

The 255 questions limit still applies.
