### ISSUE TITLE
PR Template Question unclear

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#214]
I wrote:

> ## What new work does this PR create?

What I meant was: 

 - What will you or someone else now have to do that wasn't needed before?
 - What future work are we committing to because of this PR?

Apparently that was not clear.

Is this a bad question? Is there a better way to say it?

**Comment by troublemagnet** [comment]
@adammichaelwood  Oh sir now when you specify what it means to ask, I can relate. However when I filed a PR I misinterpreted it as what new work has been done in the PR. And I was going to file an issue about duplication of the question because the first one was pretty similar. But now it makes sense. However 
> What future work are we committing to because of this PR?

conveys it more clearly, that's what I feel.

**Comment by lognaturel** [comment]
Agreed with @troublemagnet!

**Comment by nadaa** [comment]
Maybe you can say " What issues might this PR open?".
