### ISSUE TITLE
Update external links as reference to docs

### ISSUE THREAD

**Issue by ankita240796** [opendatakit/docs#261]
External links need to be replaced as reference to doc as the docs are being updated. 

**Any pull requests for this issue should use addresses instead of closes since docs are being continuously updated.**

**Comment by ankita240796** [comment]
@opendatakit-bot claim

**Comment by ankita240796** [comment]
@opendatakit-bot unclaim

**Comment by jaredbhatti** [comment]
I believe this issues is fixed. Can you close?

**Comment by ankita240796** [comment]
Yes, I think we can close this one but we need to make sure that any external link is replaced by reference to docs if there is an update!

**Comment by yanokwa** [comment]
I understand what this issue is about now. There are links in the docs (e.g., `https://opendatakit.org/use/aggregate/tomcat-install/#Configure_for_Network_Access>`) that go out to opendatakit.org, and get directed back to docs.opendatakit.org. 

You can find a list of those redirects here: https://github.com/opendatakit/website/blob/master/s3_website.yml. We have to take all the `host_name: docs.opendatakit.org` entries and make the links in the current docs go to the local links instead of going to opendatakit.org. 

A good first pass would be searching for any links in the docs that go to `https://opendatakit.org/use/*` because most of those get redirected to docs.

**Comment by jaredbhatti** [comment]
Looking through https://github.com/opendatakit/website/blob/master/s3_website.yml, the redirects are from:
https://opendatakit.org/use/*
https://opendatakit.org/help/*

There are 4 old blog posts that have links to these, which all appear to be correctly redirected.

**Comment by yanokwa** [comment]
I've reviewed `opendatakit.org/use/` and `opendatakit.org/help` and I think we've caught all the problems. Thanks all!
