### ISSUE TITLE
Add PDF output

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#271]
We *could* build a PDF as part of the build process, and make it available at some URL
This came up in the forum.

I don't know if it is actually a good idea:

 - The docs change enough that I don't know whether a PDF would be valuable
 - Some amount of work would be required to get the PDF template just right, so the value has to be weighed against that work

@yanokwa would have to add pdf deploy and build steps to circleCI, 
I, or someone else with some LaTeX experience would have to futz with the template.

**Comment by yanokwa** [comment]
A lot of our users don't have a great connection and outdated docs are better than no docs. Further, this might be a reasonable thing for a contributor to take on.

To let people know that the PDF isn't up-to-date, we could put something in the footer that says 
> ODK software is always being updated, so this PDF is likely out of date. Get the latest docs guide at https://docs.opendatakit.org.

**Comment by troublemagnet** [comment]
@adammichaelwood Sir may I start working on it?

**Comment by adammichaelwood** [comment]
Have you used LaTeX before?
Let me look into what the output looks like by default and how easy/hard it is to adjust.

Setting up LaTeX locally is a real pain, and could turn into a day long black hole of frustration for you if you haven't done it before.

(I have been through that black hole, and have it installed locally currently.)

**Comment by adammichaelwood** [comment]
Well... I fell into the LaTeX black hole... again.

I've tried three different ways to produce a PDF, and spent some amount of time attempting to debug them. 

 - [Sphinx's LaTeX builder](http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.latex.LaTeXBuilder). -- This did produce `.tex` output, but I couldn't get it to render to PDF.
 - [Rinoh plugin, a LaTeX-free PDF builder for Sphinx](https://github.com/brechtm/rinohtype) -- This hangs on a KeyError I cannot track down the cause of.
 - [Pandoc](https://pandoc.org/) -- A Haskell command line tool which translates between document types. In this case, I built the whole site as a [single page HTML file](http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.html.SingleFileHTMLBuilder), and then ran Pandoc on that. Pandoc's PDF builder relies on LaTeX... so we're back to... I can't get LaTeX to run properly.

Note:

One of the problems I encountered was that one of those builders (I think it was rinoh) could not find the images. This is because, for some reason, it didn't recognize the `file.*` syntax. So, I had to change all of those wildcard image file references to the absolute file name. 

That solved the problem, but there were others I could not overcome.

If anyone else working on this comes across the problem with the image file references, you can use [this Python script I wrote](https://gist.github.com/adammichaelwood/530c9a6add9a4b25e47882f1888d4bed), which will change all the references to include the extension. Just drop it into the root dir and run it. (I recommend doing a commit right before this so you can easily rollback if there is some kind of problem.)

(If it turns out the extensions are required in whatever PDF build process we end up with, we'll need a commit that changes them all and also updates the contributor guide to including them rather than the wildcard.)


@troublemagnet Feel free to give this a whirl. 
You *might* want to try setting this up in a VM or Docker container. (Ubuntu)
My experience with LaTeX suggests this is the best way to avoid config nightmares...

**Comment by yanokwa** [comment]
I already spoken to @adammichaelwood about this, but just so we have a record, other things to try are...
* rst2pdf - http://rst2pdf.ralsina.me/stories/index.html
* generating an epub and converting that to PDF

**Comment by troublemagnet** [comment]
@adammichaelwood  , @yanokwa  thank you sir. I'll look into these tools.

**Comment by adammichaelwood** [comment]
@troublemagnet rst2pdf looks promising, as it explicitly supports Sphinx.
Why don't you try that and see if you can get meaningful output.

**Comment by Divya063** [comment]
@adammichaelwood  I guess LaTeX output would give more professional look as compared to the output rendered with rst2pdf.[Here](https://drive.google.com/file/d/0ByddvU1PKkWaV3k3SHJTRlFJWW8/view?usp=sharing) is the pdf output generated by me(without images).Some edits are needed

**Comment by troublemagnet** [comment]
@Divya063 the images are disproportionate and the different admonitions are not styled properly either.

**Comment by adammichaelwood** [comment]
@Divya063 is that LaTeX output.

It does look better than the rst2pdf output, but they both have problems.

Anyone up for solutions to problems? Either tool is fine if we can make it work.

**Comment by yanokwa** [comment]
@Divya063 @troublemagnet Thanks to both of you for your efforts so far! I prefer the latex output because the PDF is smaller (3.8MB vs 86.7MB) and the links are pretty nice.

**Comment by Divya063** [comment]
@adammichaelwood I used Rhino to generate the pdf in the style of LaTex .The key error you were getting, I tracked it down and fixed it.The styles can be customized.

**Comment by troublemagnet** [comment]
@adammichaelwood the key error is due to line no 1135 in contributing.rst due to code block and csv table being inside a note. I'm attaching images of the actual behavior and what it is like in @Divya063's pdf (she removed the code-block directive). Also Rinoh does provide support for styling. If we alternatively represent the information(line# 1132-1150 in contributing.rst), we can go ahead with Rinoh. 

![actual](https://user-images.githubusercontent.com/28952053/31664400-df04de0c-b362-11e7-9d1f-f3023faff67c.png)
![your](https://user-images.githubusercontent.com/28952053/31664412-e9d21a70-b362-11e7-95b1-406ac173f23e.png)

**Comment by Divya063** [comment]
@troublemagnet Thanks for the elaboration, This is exactly what I did, as the build was failing at contributing.rst file, I tried to track the error in in this file and indenting that part worked.However, I didn't notice that there was a difference from the expected behaviour.Thanks for pointing out!

**Comment by troublemagnet** [comment]
@adammichaelwood the rinoh output definitely looks more professional sir but do you suggest to make a change in the note? If yes, I could work on representing the information in an alternative way and produce the new pdf for reviewing.

**Comment by adammichaelwood** [comment]
I think working out the kinks in the PDF process is going to be a long project. A few of you have included it in the Outreachy proposal, and I think that is the best venue for working on it.
(If someone who didn't include it is selected, they might *still* work on it during that period.)

So... If I were you, I would not work on it at this time.

**Comment by troublemagnet** [comment]
To go through all the pages and verify whether the produced output conveys what we intended to convey and if it doesn't, then making the change in styling would take a fair amount of time. You're right, it makes sense to do it as a part of outreachy.

**Comment by brechtm** [comment]
If you encounter any issues with using the rinohtype Sphinx builder, please create a bug report on it's [GitHub page](/brechtm/rinohtype). I've already created one for the `image.*` handing (brechtm/rinohtype#119 - fixed). @Divya063 created one related to handling of the custom video directive ((brechtm/rinohtype#118).

There are two other issues I've seen to far:

- The images are too large. rinohtype sizes images based on the DPI information contained in the image, or a default of 72 pixels/inch. Since the screenshots have a high resolution (1080×1920) and have a DPI of 72, they are rendered very large. rinohtype limits their width to the available width (but not height, yet). You need to manually set a DPI, scaling factor or width/height for the images to fix this. This can be done in the reStructuredText source, or in a rinoh stylesheet. It might be possible to configure this for all images in a single stylesheet rule, but I need to verify this.
- Rendering the complete document gets stuck in an infinite loop. I'll investigate this.

**Comment by Divya063** [comment]
@brechtm Thank you for looking into this matter and for your time. Adding [those lines](https://github.com/brechtm/rinohtype/issues/118#issuecomment-366475518) in video.py worked. 

> Rendering the complete document gets stuck in an infinite loop. I'll investigate this.

I was also stuck on this issue. After using [this python script](https://gist.github.com/adammichaelwood/530c9a6add9a4b25e47882f1888d4bed)  to handle `image.*`,  document rendering gets stuck on page 10.

![screenshot from 2018-02-18 07-16-33](https://user-images.githubusercontent.com/21216969/36352976-500f3702-14e6-11e8-9909-d364a139b282.png)
