### ISSUE TITLE
Should we have an Upgrade Note admonition?

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#302]
#297 added a new admonition style for Upgrade Notes.

I'm not sure this is a good idea, but I merged the PR because the information was good and I wanted it to get published.

FIRST - I am going to let @ankita240796 make a case for adding it.
THEN - I will mention my concerns.
AND THEN - others may comment.

Please note:
 
 - Do not comment until @ankita240796 and @adammichaelwood (me) have both commented.
 - This is not a democracy. The point of a discussion is to arrive at a good decision, not to vote on a course of action.
 - This is also not a dictatorship. You can disagree with me.

**Comment by ankita240796** [comment]
# Reasons to add this:
- Any information related to upgrade process is written separately and thus will be more clear.
- User can directly view upgrade information when required as this will be visible clearly in every section.
- They can be preferred over a subsection since upgrade information will be added about every version and having a separate admonition will enhance readability.
# Difference between upgrade notes and notes admonition
- Upgrade notes consist of a set of points which will guide about upgrade process and things to take care while upgrading.
- Any other information not related to upgrading is mentioned in normal notes.
- For example
> upgrade notes :  
> MySQL and PostgreSQL require special upgrade instructions. The `_filter_group` table has a new column. If you are running ODK Aggregate 1.0 or 1.1, you will need to issue an `alter table` command on this table to add this column.
> notes:
> The use of LONGBLOB and LONGSTRING requires a configuration change in the MySQL server. 
# Cases where upgrade notes will be used
- Whenever any doc related to upgrading is created, all the information which describes upgrade process will be added in upgrade notes.
- Any specific tips to be kept in mind during upgrading will be added in upgrade notes.

**Comment by adammichaelwood** [comment]
My concerns here are:

 - I'm not sure it is clear when to use an Upgrade Note instead of a regular Note. The difference isn't obvious or easy to apply consistently. For example, this image shows two notes, and I'm not sure why one is an Upgrade note and the other isn't.

![screen shot 2017-10-20 at 4 41 35 pm](https://user-images.githubusercontent.com/1776241/31845458-c1335e26-b5b5-11e7-809e-aaadccea6ef2.png)

 - I worry about the precedent of creating new, purpose-built admonitions. How often will we do that? What sorts of things are important enough to warrant it?

 - Every other software project that uses Sphinx also has upgrades and notes, and has seemed to get along fine without Upgrade Notes.
    - My general feeling about software is: Don't add things unless they are *really* needed.

**Comment by ankita240796** [comment]
Yes, @adammichaelwood you are right that this admonition is not really needed. It was just an idea to make the Upgarde notes more readable as Aggregate upgrade is a really long doc. The difference between the two notes here is that the first note gives a piece of information about rev 210 sync protocol but the second note specifies that when should upgrade be avoided. If we continue using this, the difference will slowly become clear. Though these notes are not actually needed but their use can enhance the readability of long Upgrade docs.
Further their absence will not affect the docs in any way, so, if you want to remove them, I will do that.

**Comment by lognaturel** [comment]
In a case like #337, I feel strongly that the version information should be readily available right when the feature is introduced and I've shown one way that could be done. I now realize this may not have been part of what you wanted to discuss in this issue, though.

In the case of upgrade notes, I don't feel as strongly. I can see arguments for both and so my tendency would be to go for the simpler solution and only have one kind of note!

**Comment by ankita240796** [comment]
Yes, I agree here that upgrade notes are not mandatory but on the other hand, they are also not difficult to include. There is no extra maintenance required since the admonition is defined and we can use them as required.
