### ISSUE TITLE
xlsform offline and audio audit type.

### ISSUE THREAD

**Issue by fabla** [opendatakit/docs#314]

**Comment by lognaturel** [comment]
Same message as in #313 -- this is not the right place for ODK feature requests!

I see that in the issue comment you have left the following message:
> can the xlsform be upgrated to be able to convert xlsform to xform with the type **audio audit** and **text audit**

It sounds like those are new feature requests. If you'd like to post those to https://forum.opendatakit.org/ please describe the functionality that you would like. For example, "I want the recording to start when the user does X and stop when the user does Y. Since audio files will be huge, they shouldn't be sent with the form." etc.
