### ISSUE TITLE
Add spell check on PRs

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#434]
I was just noticing that we have some spelling errors. It'd be great if we could add a spell check (perhaps as part of the sphinx-build) that would warn when a build has spelling mistakes. 

An ideal solution would integrate into sphinx, be an active/healthy project, and give us the option to warn or fail on projects, and allow us to ignore some words.

@ankita240796 this might be a good issue for you to take on when you have some time!

**Comment by adammichaelwood** [comment]
[aspell](http://aspell.net/) seems to be the standard GNU/Linux tool.

(I just integrated this locally into my emacs set up so now at least I'll be made aware of my own spelling errors as I type...)

There are Python bindings for it, or it can just be run from a bash script.

The tricky part is what to do with feedback. Spell check works best at authoring-time,
because human judgement is often needed.
So incorporating it into the test-deploy process will take some thinking...

**Comment by ankita240796** [comment]
I will take this up once I am done with the style guide thing.

**Comment by adammichaelwood** [comment]
I mentioned I've started using aspell locally.
I think it's the best/easiest open source solution.

Things to consider:

 - custom dictionary, preferably in the repo (I don't know the source format of aspell custom dictionaries, or how readable they are --- but we'd need to be able to review additions easily)
 - ignoring lines -- inside code blocks etc. -- this is not natively part of aspell
 - what do we do about errors? do they break the build?

**Comment by ankita240796** [comment]
Maybe errors should break the build since spelling mistakes for sure need a fix.

**Comment by yanokwa** [comment]
I'm also voting for breaking the build. 

@adammichaelwood I'm surprised there isn't something turnkey for this. Might be good to ask in the Write the Docs slack? Best I've found is https://doughellmann.com/blog/2011/05/26/creating-a-spelling-checker-for-restructuredtext-documents for pychant.

**Comment by ankita240796** [comment]
@opendatakit-bot I will be working on this in some time.

**Comment by ankita240796** [comment]
@opendatakit-bot I am working on it.
