### ISSUE TITLE
Document how to add color and styling to Forms

### ISSUE THREAD

**Issue by smoyth** [opendatakit/docs#518]
https://nafundi.com/blog/posts/customize-odk-forms-with-fonts-colors-sizes-and-links/

Is this all still possible?

**Comment by adammichaelwood** [comment]
I believe this is still possible. And this info, cleaned up a bit, might be a good addition to the Form Building section.

**Comment by lognaturel** [comment]
http://xlsform.org/#styling This somewhat ties into the conversation at #239 -- how much from the specification docs should be repeated in these docs.

**Comment by hooverlunch** [comment]
How about all of it? XLSForm and XForms are such central pieces of Collect that it seems quite confusing to not have them in the ODK docs. I bet only about 5% of people have enough knowledge and experience to remember that they are separate standards and so of course they have separate doc sites. (Don't count me in that 5% either!)

The docs are all CC licensed right? So that shouldn't be a problem?

As for the actual technical piece of including them, could use subrepos or some sort of script that copies the content with each new docs release or somesuch. If they're not in compatible formats right now we could make them so...
