### ISSUE TITLE
The word "aesthetic" does not have a supported spelling.

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/docs#546]
The word aesthetic will fail the style check, which will suggest the word be spelled "esthetic". But if that spelling is used, the spell checker will fail.

**Comment by adammichaelwood** [comment]
Does it fail the style check on the grounds that it is British instead of American?
I think we should remove that as the `ae` spelling is well attested.

A little bit of research suggests that both are correct, and that many people (though certainly not all) prefer `esthetic` when speaking of cosmetology and `aesthetic` when speaking of philosophy.

I'm not sure when either of these contexts would come up in our docs, but the spell/style checkers should allow both.
