### ISSUE TITLE
Video sphinx directive 

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#66]
Currently, images get stored at `img`, but videos are stored at `_static/vid` and it's not clear why. Unless there is a good reason, we should standardize on the location.

**Comment by yanokwa** [comment]
This is likely related to the appearance of a `build/_images` folder when Sphinx is run and thus is related to https://github.com/opendatakit/docs/pull/67. Can you offer an explanation, @adammichaelwood?

**Comment by adammichaelwood** [comment]
The "good reason" is that it is currently the only way to do it.

Sphinx copies images from wherever they are stored to the `/_images` dir as part of the build process. It doesn't copy the entire `/img/` folder -- it copies the image when it finds the `.. image` or `.. figure` directive. 

OTOH - the video files are currently in `_static` -- Sphinx copies over the entire `_static` dir on build (it's typically used for custom CSS and JS files. And I am inserting videos with raw HTML... which is *wrong* (from an aesthetic and consistency standpoint) but the only current way to do it, as Sphinx doesn't  have a `.. video` directive.

The *right* way to do this would be to create a Sphinx plugin to handle video. It would then do precisely what the `.. image` directive does: output proper markup and copy the file over. This would be a benefit because it would be consistent across media types. It would also benefit the larger Sphinx community, as this is something other people need to.

But I don't know that we want to take the time to write and then maintain a Sphinx plugin. I don't *think* it is that big of a deal, and I've been wanting to do it for a while, but we all know how quickly "it's just 100 or so lines of code" becomes a gigantic time sink.

So....  

The real question is: Does anybody *really* mind the current situation, which is:

 - files stored in more than one place in the repo 
 - two different markup constructions for images and video

And, is it worth a day or so of work to fix those two problems?

**Comment by yanokwa** [comment]
Thanks for explaining this, Adam. 

I don't think it's a good use of time to change the current behavior. Or rather, maybe this is the kind of thing a contributor might want to take on, but it's not a priority for the core team.

**Comment by jumperskirt** [comment]
is there a python library equivalent to PIL for video?

**Comment by adammichaelwood** [comment]
Probably, but I'm not sure how that would be relevant to this issue.

Could you clarify what you are considering?

**Comment by jumperskirt** [comment]
looking at the [image directive](http://repo.or.cz/docutils.git/blob_plain/refs/heads/master:/docutils/docutils/parsers/rst/directives/images.py), the PIL.Image seems to do the image processing, but as PIL does not support mp3 or mp4 file formats, i was trying to figure out whether using a library like moviepy to do the video processing in the video directive would make sense

**Comment by adammichaelwood** [comment]
I think a video directive doesn't need to be as complicated.

It seems to me a video directive would only need to:

 - copy video over to output
 - generate the appropriate html for the output
 - *perhaps* generate some alternate text output for non-html builders

**Comment by jumperskirt** [comment]
hm would the video.py module then look something like [this](https://gist.github.com/jumperskirt/3ac22616b705082dbbfc188a9cdd6871)?

**Comment by adammichaelwood** [comment]
It's hard to tell from a gist. (I don't see where you explicitly output the `<video>` html markup... but maybe that's already dealt with in the HTML builder (?) ).

I'd be thrilled to see a PR that included this, so we could test it.

**Comment by jumperskirt** [comment]
right! i put that in the conf.py file under the setup function, but i suspect that is not correct (when i try to build with the code i've added, there are many error messages, indeed). i will submit a pr and would sure appreciate any guidance towards fixing said errors
