### ISSUE TITLE
Testing framework for Python code

### ISSUE THREAD

**Issue by windwardrail** [opendatakit/docs#818]
Add a testing framework for Python code and integrate it with the Makefile.

**Comment by windwardrail** [comment]
@opendatakit-bot claim

**Comment by windwardrail** [comment]
@opendatakit-bot claim --force

**Comment by yanokwa** [comment]
@windwardrail Can you please write a bit more about why the lack of a testing framework is a problem? Without that context, we can't really evaluate whether or not a PR that closes this issue is a good idea.

**Comment by windwardrail** [comment]
Custom Python code is being utilized in various places in the docs repo such as in the style checker. As a general best practice, code should be tested. Among other things, tests provide a proof point when attempting to resolve an issue such as #596 for example. A test can show that the issue has in fact been resolved and in the process of resolving, has not become broken in a different way.

Tests need a consistent home and modality within in a project. My suggestion would be to keep tests in a `tests` directory and to use `Pytest` as the test runner and `Hypothesis` as the standard testing modality.

`Hypothesis` is a property based testing framework. Property based testing is a very powerful technique and effectively forms a superset of unit-style testing.

If there is acceptance around these choices, this issue should be considered closed based on the conditions of having a tests directory with some trivial example test that proves a working test framework is in place. This will lay the groundwork for writing actual tests of project code.

**Comment by adammichaelwood** [comment]
@windwardrail and I talked about this in person, but I should have come back yesterday and documented some of that conversation also...

Two points to consider:
 - is testing needed, and why?
 - how to do testing?

### Is testing needed, and why?

Just by default, I think YES is the right answer, all the time. We have a bunch of custom build code that is a bit fragile, and no way of proving that it works currently for all case, or ensuring  that we don't accidentally break things if we extend, refactor, or upgrade.

More specifically, we have a few specific cases that would strongly benefit from testing. For example...

 - Devin mentioned #596. Any other style check false positives or false negatives that come up would be much easier to work on with testing in place.
 - #740 (Upgrade Sphinx). Having testing in place before an upgrade is *always* a good idea. Doubly so in our case because we have some custom code that is calling deprecated APIs in Sphinx. This needs to get refactored, and we should make sure we're testing before we start making those changes.
 - If we decide to add additional style checks, being able to write tests ahead of time for what we are actually going to check for would be really good practice.
 - I think we should, at some point, pull the video directive and the additional style checking into standalone modules other projects can use them. We'll need to be sure that we have testing in place as we factor out those components.

### Why Hypothesis

I'm leaning on @windwardrail's expertise in this area. But --- to the extent I have enough engineering savvy to have an opinion.... I agree with him.

The [Hypothesis docs](https://hypothesis.readthedocs.io/en/latest/) lay out the basics here:

> It works by letting you write tests that assert that something should be true for every case, not just the ones you happen to think of.
> 
> Think of a normal unit test as being something like the following:
> 
> 1. Set up some data.
> 2. Perform some operations on the data.
> 3. Assert something about the result.
> 
> Hypothesis lets you write tests which instead look like this:
> 
> 1. For all data matching some specification.
> 2. Perform some operations on the data.
> 3. Assert something about the result.
> 
> This is often called property based testing, and was popularised by the Haskell library Quickcheck.

This seems much more reasonable than the "try to think of every edge case and permutation" method we would follow if we were using something more conventional like [`unittest`](https://docs.python.org/3/library/unittest.html) from the standard library.

Also, I think this approach is particularly useful for our context (testing code that that operates on lightly structured natural language prose), because the input space is so open to variation and weirdness.

#### Any reasons against?

My default concerns in using something outside the standard library are:

 - is it well maintained?
 - is it well documented?

The answer to both questions seems to be YES.

The other thing I'm concerned about is:

 - How easy will tests be to write, understand, and maintain?

My understanding is that test case code is much smaller in Hypothesis, because each assertion covers a wide range of permutations you would otherwise need to hand write. So I *think* that it will probably be comparatively easier. (Not necessarily *easy* in absolute terms. Just easier than the alternative. Testing is hard.)

On the other hand, abstracting the input space to a set of executable conditions is more complicated than just writing examples of good and bad input. This means writing complete tests will require a little more thought and skill than would be the case in a more conventional testing framework.

That being said, I think this downside is mitigated by the fact that we can *also* write and use conventional example cases. This would allow us to have a test case writing flow like:

 1. Brainstorm/explore the input space by writing conventional examples of good/bad input. (At this point, tests can be run.)
 2. Conversation/thinking around what those examples imply.
 3. Refactor test cases to abstract/programmatic inputs. (We could remove or retain the original plain-text examples, depending on what seems prudent as we move forward.)

#### The proof of the pudding is in the coding...

I think a handful of example test implementation will tell us more about the usefulness/ease/power of Hypothesis in particular than further conversation would. So...

My suggestion is to move forward with the initial PR on this (#819) and see how we feel after @windwardrail contributes a couple examples.
