### ISSUE TITLE
Style testing on individual files seems to be broken

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#844]
I tried the commands provided in the contributor guide:

```
python style.py path-to/file.rst
```

That didn't work. 
I tried it with `-r` (which is, according to the code, required)

```
python style.py -r path-to/file.rst
```

That didn't work.

I tried every variation of the path argument I could think of, 
with and without the `-r`.

```
path-to/file.rst
/path-to/file.rst
./path-to/file.rst
file.rst
path-to/file
/path-to/file
./path-to/file
file
```

None of those worked.

The result in all the `-r` cases was a message: `No files to check for!`
All the cases without `-r` just told me I had to include `-r`.

I tried editing `style-test.py` to make `-r` not required. 
When I ran it without `-r` after that, it just created a bunch of errors.

### More details

Note: This entire git/gitpython section might be completely irrelevant.
I have looked at the diff of `requirements.txt`, and it looks like it didn't include `git` and did include `gitpython` all along. So I'm not sure what was causing the problem for me locally. I'm only leaving this section here as a reference in case something weird with Python/git happens in the future and we start searching for clues.

`style-test.py` imports `git` (which was listed in `requirements.txt` - though I have removed it in a recent PR).

Running style-test without `git` threw a ModuleNotFoundError.
I could not `pip install -r requirement.txt` because of `git` --- pip could not find it.
I tried `pip install git` (in case the version listed in `requirements.txt` was no longer available.
That didn't help either.

I corrected this by pip installing git-python,
which *seems* to be a drop in replacement
(you can import it with `import git`, 
so I didn't have to change any code).

It did not, though, fix any of the problem mentioned above.
(I didn't attempt running with `-diff`, 
so the git module issue is not related.)

### Directory-based checking works

I ran the tester on an entire source directory.
Works fine there.

### Let's test this stuff

I think it would be a good idea to build some failing tests for what is broken
(as well as some passing tests for the stuff that still works)
and try to get ourselves onto a test-driven development approach,
which we have been sorely lacking.

It would be good for whoever works on this (@ankita240796?) 
to talk to @windwardrail about the new testing infrastructure.

**Comment by ankita240796** [comment]
Hi @adammichaelwood, I tested this. It works fine with the following command:
`python3 style-test.py -r odk1-src filename.rst`

Since we introduced two different directories for ODK1 and ODK2 docs, a feature for providing source directory was added as required here: https://github.com/opendatakit/docs/pull/480/files#diff-03f91a1463f33e40d7cc2ad6fb5bfddeR276

So, to run test on a specific file, we need to provide the source directory name with the required option `--src_path` followed by the filenames.

**Comment by ankita240796** [comment]
Hi @adammichaelwood, I tested this. It works fine with the following command:
`python style-test.py -r odk1-src filename.rst`

Since we introduced two different directories for ODK1 and ODK2 docs, a feature for providing source directory was added as required here: https://github.com/opendatakit/docs/pull/480/files#diff-03f91a1463f33e40d7cc2ad6fb5bfddeR276

So, to run test on a specific file, we need to provide the source directory name with the required option `--src_path` followed by the filenames.

**Comment by adammichaelwood** [comment]
Got it. Thanks. I will update the guide accordingly.
